Repository xrnl/aginun, pull requests merged in 2020-02, with the labels that each got.

#4 Selection Filters + small accessibility fixes
  src/components/AutocompleteCustom.vue
  src/components/FilterDrawer.vue
  src/components/RoleCard.vue
  src/components/TheAppBar.vue
  src/components/TitleSubtitle.vue
  src/components/layout/FilterDrawerSection.vue
  src/components/layout/FlexWrapper.vue
  src/store/modules/localGroups.js
  src/store/modules/roles.js
  src/store/modules/workingGroups.js
  src/views/Explore.vue
Labels: enhancement

#11 Role detail view
  src/App.vue
  src/components/FilterDrawer.vue
  src/components/layout/FlexWrapper.vue
  src/components/layout/MetaInfo.vue
  src/components/roles/RoleCard.vue
  src/components/roles/RoleViewDialog.vue
  src/router/index.js
  src/store/modules/roles.js
  src/views/RolesOverview.vue
Labels: enhancement, frontend

#10 Prettier setup
  package-lock.json
  package.json
Labels: meta

#27 correct prettier parser
  package.json
Labels: bug
